### ISSUE TITLE
Suggestion for README and GitHub repo

### ISSUE THREAD

**Issue by melodykramer** [wikimedia-research/Discovery-Search-Test-BM25#1]
Hello!

Two small things that might make this easier for the end user.
1. Including this link in the description: https://wikimedia-research.github.io/Discovery-Search-Test-BM25/ and README
2. Putting licensing/CC information in README.md so that users know that this is forkable / available for use. 

I am happy to handle 2. but don't think I'm credentialed to do 1. :)

Mel

**Comment by bearloga** [comment]
Thank you for the suggestions!
